export const SET_SIGN_UP_STATUS = "SET_SIGN_UP_STATUS";
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";

export const FETCH_USERS = "FETCH_USERS";
export const FETCH_SERVICE_TYPES = "FETCH_SERVICE_TYPES";
export const FETCH_USER_SERVICE_TYPES = "FETCH_USER_SERVICE_TYPES";
export const FETCH_USER_SERVICE_TYPES_BY_SPECIALIZATION =
  "FETCH_USER_SERVICE_TYPES_BY_SPECIALIZATION";
export const REDIRECT_TO_BOOKING_PAGE = "REDIRECT_TO_BOOKING_PAGE";
export const GET_PROVIDER_TO_BOOKING_PAGE = "GET_PROVIDER_TO_BOOKING_PAGE";

export const GET_SERVICE_TO_BOOKING_PAGE = "GET_SERVICE_TO_BOOKING_PAGE";
export const GET_USER_TO_BOOKING_PAGE = "GET_USER_TO_BOOKING_PAGE";
export const ORDER_BOOKING = "ORDER_BOOKING";
